spring:
  application:
    name: trade-app
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      ssl:
        enabled: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
